apiVersion: 1

groups:
  - orgId: 1
    name: 'RPC-Alerts'
    folder: 'RPC-Alerts'
    interval: 1m
    rules:
      - uid: lJzM570Vk
        title: Gnosis Distance
        condition: threshold
        data:
        - refId: rpc_diff
          queryType: ''
          relativeTimeRange:
            from: 3600
            to: 0
          datasourceUid: P1809F7CD0C75ACF3
          model:
            datasource:
              type: prometheus
              uid: P1809F7CD0C75ACF3
            editorMode: code
            expr: (last_over_time(latest_block{job="gnosis_latest"}[1h]) - on (instance, blockchain)
              last_over_time(current_block{job="gnosis_current"}[1h]))
            hide: false
            interval: ''
            intervalMs: 15000
            legendFormat: __auto
            maxDataPoints: 43200
            range: true
            refId: rpc_diff
        - refId: rpc_diff_last
          queryType: ''
          relativeTimeRange:
            from: 3600
            to: 0
          datasourceUid: "-100"
          model:
            conditions:
            - evaluator:
                params:
                - 0
                - 0
                type: gt
              operator:
                type: and
              query:
                params: []
              reducer:
                params: []
                type: avg
              type: query
            datasource:
              name: Expression
              type: __expr__
              uid: __expr__
            expression: rpc_diff
            intervalMs: 1000
            maxDataPoints: 43200
            reducer: last
            refId: rpc_diff_last
            settings:
              mode: ''
            type: reduce
        - refId: threshold
          queryType: ''
          relativeTimeRange:
            from: 3600
            to: 0
          datasourceUid: "-100"
          model:
            conditions:
            - evaluator:
                params:
                - 25
                - 0
                type: gt
              operator:
                type: and
              query:
                params: []
              reducer:
                params: []
                type: avg
              type: query
            datasource:
              name: Expression
              type: __expr__
              uid: __expr__
            expression: rpc_diff_last
            intervalMs: 1000
            maxDataPoints: 43200
            refId: threshold
            type: threshold
        updated: '2023-02-03T16:43:52Z'
        noDataState: Alerting
        execErrState: Error
        for: 5m
        dashboardUid: 9XH7Fn0Vk,
        panelId: 2
        annotations:
          __dashboardUid__: 9XH7Fn0Vk
          __panelId__: '2'
        labels:
          notification: chain_diverge
      - uid: lJzM570Va
        title: Polygon Distance
        condition: threshold
        data:
        - refId: rpc_diff
          queryType: ''
          relativeTimeRange:
            from: 3600
            to: 0
          datasourceUid: P1809F7CD0C75ACF3
          model:
            datasource:
              type: prometheus
              uid: P1809F7CD0C75ACF3
            editorMode: code
            expr: (last_over_time(latest_block{job="polygon_latest"}[1h]) - on (instance, blockchain)
              last_over_time(current_block{job="polygon_current"}[1h]))
            hide: false
            interval: ''
            intervalMs: 15000
            legendFormat: __auto
            maxDataPoints: 43200
            range: true
            refId: rpc_diff
        - refId: rpc_diff_last
          queryType: ''
          relativeTimeRange:
            from: 3600
            to: 0
          datasourceUid: "-100"
          model:
            conditions:
            - evaluator:
                params:
                - 0
                - 0
                type: gt
              operator:
                type: and
              query:
                params: []
              reducer:
                params: []
                type: avg
              type: query
            datasource:
              name: Expression
              type: __expr__
              uid: __expr__
            expression: rpc_diff
            intervalMs: 1000
            maxDataPoints: 43200
            reducer: last
            refId: rpc_diff_last
            settings:
              mode: ''
            type: reduce
        - refId: threshold
          queryType: ''
          relativeTimeRange:
            from: 3600
            to: 0
          datasourceUid: "-100"
          model:
            conditions:
            - evaluator:
                params:
                - 25
                - 0
                type: gt
              operator:
                type: and
              query:
                params: []
              reducer:
                params: []
                type: avg
              type: query
            datasource:
              name: Expression
              type: __expr__
              uid: __expr__
            expression: rpc_diff_last
            intervalMs: 1000
            maxDataPoints: 43200
            refId: threshold
            type: threshold
        updated: '2023-02-03T16:43:52Z'
        noDataState: Alerting
        execErrState: Error
        for: 5m
        dashboardUid: 9XH7Fn0Vk,
        panelId: 2
        annotations:
          __dashboardUid__: 9XH7Fn0Vk
          __panelId__: '2'
        labels:
          notification: chain_diverge
