{
 "title": "RPC",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(current_block, job)"
    }
   },
   {
    "name": "blockchain",
    "query": {
     "query": "label_values(current_block{job=\"$job\"}, blockchain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "job" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(current_block{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase((current_block{job=\"$job\"} > 0)[1h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(latest_block[1h]) - on (instance, blockchain) last_over_time(current_block{job=\"$job\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(last_over_time(latest_block[1h]) - on (instance, blockchain) last_over_time(current_block{job=\"$job\"}[1h])) / on (instance, blockchain) increase((current_block{job=\"$job\"} > 0)[1h:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$blockchain",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "current_block{job=\"$job\"} != 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "latest_block and on (instance, blockchain) current_block{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 } }
   ]
  }
 ]
}